Swift 3 support
Weebly/Cereal pull request #26
Opened 2017-03-11 00:11 UTC by Sega-Zero

Full swift 3 support based on Cereal 2.0, finally :)

2017-03-13 21:33 UTC, ketzusaka commented on Cereal/CerealDecoder.swift
> +    fileprivate func itemForKey(key: String) -> CoderTreeValue? {
This should be `itemForKey(_ key: String) -> CoderTreeValue?`. We shouldn't need to duplicate the word `key`.

2017-03-13 21:34 UTC, ketzusaka commented
I think the enums should of remained without an argument label for the associated values. I think the enum is descriptive enough, and the documentation that Apple gives doesn't have an argument label on associated values: https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html

2017-03-13 21:42 UTC, Sega-Zero commented on Cereal/CerealDecoder.swift
> +    fileprivate func itemForKey(key: String) -> CoderTreeValue? {
I think this should be `itemFor(key:)`, according to new swift guidelines, will patch it asap

2017-03-13 21:46 UTC, ketzusaka commented on Cereal/CerealDecoder.swift
> +    fileprivate func itemForKey(key: String) -> CoderTreeValue? {
Hmm, I'm fine with either, but `itemForKey(_` is more in line with how Apple imports `NSCoder`

2017-03-13 21:53 UTC, Sega-Zero commented on Cereal/CerealDecoder.swift
> +    fileprivate func itemForKey(key: String) -> CoderTreeValue? {
But it's a `fileprivate` method :) Also, `NSCoder` has no itemForKey method, afaik.

2017-03-13 22:02 UTC, Sega-Zero commented
I thought I removed all the associated value labels, where did I missed it?

2017-03-13 22:06 UTC, ketzusaka commented
Oh god, nevermind that. They are removed on the enums. I mistook `CerealDecoder.____` as an enum case. In any case, I think things like `CerealDecoder.rootCerealItemsWithData` should actually be `CerealDecoder.rootCerealItems(with data: Data)`

2017-03-13 22:08 UTC, Sega-Zero commented
Agree. Renaming will take some extra time :)

2017-03-13 23:06 UTC, Sega-Zero commented
Should I rename CerealEncoder's `dataWithRootItem(_ root: ItemType) throws -> Data {` to
`data(with rootItem: ItemType) throws -> Data {`?

2017-03-13 23:07 UTC, ketzusaka commented
Yeah, and all the other `dataWith______` calls please :)

2017-03-13 23:33 UTC, Sega-Zero commented
Had to rename to `data(withRoot:)`, because without `root` in parameter name it becomes unclear what kind of value the function expects.

2017-03-16 10:31 UTC, Sega-Zero commented
Is there anything else? :)

2017-03-16 17:10 UTC, eddiekaiger requested changes

2017-03-16 17:10 UTC, eddiekaiger commented on Cereal/Cereal.swift
> +func identifyingCerealTypeWithIdentifier(_ identifier: String) throws -> IdentifyingCerealType.Type {
this should be `identifyingCerealType(withIdentifier identifier: String)`

2017-03-16 17:10 UTC, eddiekaiger commented on WatchExample Extension/InterfaceController.swift
> +    fileprivate func updateEmployeesWithData(_ employeeData: Data) {
`updateEmployees(withData employeeData: Data)`

2017-03-16 17:10 UTC, eddiekaiger commented on Cereal/CerealDecoder.swift
> +    fileprivate func itemFor(key: String) -> CoderTreeValue? {
`item(forKey: String)`

2017-03-16 17:10 UTC, eddiekaiger commented on Cereal/CerealDecoder.swift
> +    fileprivate static func propertiesIndexMapForType(type: Any.Type, value: CoderTreeValue) -> [String: Int] {
`propertiesIndexMap(for type: Any.Type, value: CoderTreeValue)`

2017-03-16 17:10 UTC, eddiekaiger commented on Cereal/CerealDecoder.swift
> +    func save(map: [String: Int], forType type: Any.Type) {
the label here can just be `for`

2017-03-21 18:44 UTC, Sega-Zero commented
Hope you guys merge this PR someday =)
If no more changes required, please release pod version for swift-2, swift-2.3 and the latest swift-3

2017-03-21 18:45 UTC, ketzusaka commented
Will-do. I'll look again today -- eddie's on vacation :)

2017-03-22 00:20 UTC, ketzusaka approved these changes
Looks good! Will merge tomorrow and get tags setup.

2017-03-22 17:07 UTC, merged